### ISSUE TITLE
Coherent String.h and Object.h 

### ISSUE THREAD

**Issue by edchrepo** [conorpaschenko/A1Part2#14]
In order for us and other teams to implement all 3 classes including your queue class, I think it's best to have a standardized object and string interface.

Most people in piazza are using this standardized object.h and string.h:
https://piazza.com/class/k51bluky59n2jr?cid=345

So I was wondering if you could change these two files

**Comment by james-herbstritt** [comment]
Done, thanks for the link to the post.
