### ISSUE TITLE
Remove virtual from Queue functions

### ISSUE THREAD

**Issue by hurda21** [conorpaschenko/A1Part2#15]
Since Queue doesn't have any children classes, could you remove "virtual" from the functions?

**Comment by james-herbstritt** [comment]
I think the idea is that you subclass it to implement it.

**Comment by hurda21** [comment]
Ah, I thought we had to strictly follow the structure of their API already (can only use subclasses if they have subclasses implemented).

**Comment by hurda21** [comment]
Found this post that says we should just write over the API: https://piazza.com/class/k51bluky59n2jr?cid=343

**Comment by james-herbstritt** [comment]
I got "Post cannot be found" for that link

**Comment by hurda21** [comment]
Hmm, they must have deleted it for some reason.

I just asked again on Piazza - I'll let you know when they respond.

**Comment by hurda21** [comment]
Try clicking the link above now - it's showing up for me again.

Also have confirmation from my post: https://piazza.com/class/k51bluky59n2jr?cid=406

**Comment by james-herbstritt** [comment]
Ah okay cool. Thanks that link worked. I think you are right however, we have had people request to have the methods be virtual as well #10 for example. Would like to hear @Coderrine, @frankkulak, @kyleacmooney, and @ifteda think.

**Comment by james-herbstritt** [comment]
Also I will point you to https://piazza.com/class/k51bluky59n2jr?cid=345 which seems to be an agreed upon approach using virtual for the interface.

**Comment by frankkulak** [comment]
@hurda21 @james-herbstritt I think they should remain virtual. Removing virtual would make it so we cannot subclass Queue, but being virtual allows us to make that decision for ourselves.
