### ISSUE TITLE
Remove implementation from queue.h

### ISSUE THREAD

**Issue by frankkulak** [conorpaschenko/A1Part2#2]
Queue is just supposed to be an interface, and according to [this post on Piazza](https://piazza.com/class/k51bluky59n2jr?cid=317), you will lose points if you do not remove the implementation.

**Comment by Coderrine** [comment]
I want to bump this for it to be done as quickly as possible, so that we may ask questions about the API.

**Comment by conorpaschenko** [comment]
I removed the implementation of queue.

**Comment by Coderrine** [comment]
Hi! Please remove the constructor/destructor implementation as well. Thanks!

**Comment by james-herbstritt** [comment]
Done
