### ISSUE TITLE
Tests for hash()

### ISSUE THREAD

**Issue by ifteda** [conorpaschenko/A1Part2#23]
We're not sure that it's a great idea to test that the hash codes of 2 unequal queues are not equal (e.g., line 32, line 68), only because any 2 unequal queues may potentially have the same hash code. We understand the intention of such tests, but believe the equals() tests should be sufficient to demonstrate that 2 queues are dissimilar.

**Comment by james-herbstritt** [comment]
Makes sense. Hash collision is a thing. removed assert.

**Comment by ifteda** [comment]
@james-herbstritt I think you missed one :)
