### ISSUE TITLE
Issue #23 incomplete

### ISSUE THREAD

**Issue by ifteda** [conorpaschenko/A1Part2#24]
See comment in issue #23

_Originally posted by @ifteda in https://github.com/conorpaschenko/A1Part2/issues/23#issuecomment-580543352_

**Comment by james-herbstritt** [comment]
Ah sorry, missed 68. Fixed now.

**Comment by ifteda** [comment]
@james-herbstritt @conorpaschenko Did y'all push?

**Comment by james-herbstritt** [comment]
Yeah it should be there. not seeing it?

**Comment by ifteda** [comment]
Still says last updated 4 hrs ago

**Comment by james-herbstritt** [comment]
My bad, had made the change on the wrong repository. You should be good to go now.
