### ISSUE TITLE
Missing parameter in constructor

### ISSUE THREAD

**Issue by ifteda** [conorpaschenko/A1Part2#9]
Your comments say the constructor should expect a max capacity, but the constructor has no parameters. Please add a parameter for max capacity (e.g., size_t).

On another note, I'm not sure that capacity is really necessary. So, alternatively, that and associated methods could be removed or have updated documentation.

**Comment by kyleacmooney** [comment]
I also don't think it would be necessary to initialize the queue with a max capacity.

Maybe the owners of this repo could just revise those comments?  (as well as the tests that require this parameter)

**Comment by conorpaschenko** [comment]
Capacity was removed
